### ISSUE TITLE
Windows Compatibility 

### ISSUE THREAD

**Issue by k-nayak** [Hamptonjc/Real_Time_LaneNet_Carla#2]
Hello @Hamptonjc, 
The project looks really interesting and i see that most of the work was done on Linux. I was curious to know if any one has tried this on Windows and what issues can be faced and solved while implementing in Windows 11. Hope to hear from you. Thanks.

**Comment by Hamptonjc** [comment]
This was a project I did when I was first learning Python. Never tried it with Windows, but I don't see any reason why it wouldn't.

**Comment by k-nayak** [comment]
Thanks for the response, Unfortunately, I couldn't get the data collector running for Carla 0.9.11 (one of the latest versions) and could really get to make it run on my PC.
